### ISSUE TITLE
Feature Request: Enable comments system via giscus and github discussions

### ISSUE THREAD

**Issue by Xuanwo** [PsiACE/databend-internals#1]
How about enabling comments systems via https://giscus.app/ and GitHub discussions?

**Comment by PsiACE** [comment]
Good idea.

**Comment by PsiACE** [comment]
Hi @Xuanwo , after commit  https://github.com/PsiACE/databend-internals/commit/080f004a444c7068107fd353af811e72b741158f , we have a simple giscus integration, would you like to give it a try?

**Comment by Xuanwo** [comment]
Seems cool: https://github.com/PsiACE/databend-internals/discussions/2
